import { useState } from 'react'
import { contactInfo } from '../data'

export default function Contact({onBook}:{onBook:()=>void}){
  const [done,setDone]=useState(false)
  return <>
<section className="page-hero compact"><span className="eyebrow light">Private Client Services</span><h1>Let’s discuss your<br/><em>next premium look.</em></h1><p>For senator wear, kaftans, suits, corporate dressing and custom menswear enquiries.</p></section>
<section className="contact-layout section-pad"><div><span className="eyebrow">Official line</span><h2>Chat with ZUCOL APPAREL.</h2><p>Use the enquiry form for the demo or go directly to the official WhatsApp line for quick response and order discussions.</p><div className="contact-notes"><div><b>WhatsApp</b><span>{contactInfo.phoneDisplay}</span></div><div><b>Registration</b><span>{contactInfo.rc}</span></div><div><b>Specialties</b><span>Senator Wear • Kaftans • Suits • Corporate Wears</span></div><div><b>Location & Reach</b><span>📍Abuja • 🌎 Wide Delivery</span></div></div><div className="contact-actions"><a className="button gold" href={contactInfo.whatsappLink} target="_blank" rel="noreferrer">Open WhatsApp</a><button className="button dark" onClick={onBook}>Prefer an appointment?</button></div></div>
{!done?<form className="contact-form" onSubmit={(e)=>{e.preventDefault();setDone(true)}}><input required placeholder="Full name"/><input required type="email" placeholder="Email address"/><input required placeholder="Phone / WhatsApp number"/><select defaultValue=""><option value="" disabled>Type of enquiry</option><option>Senator wear</option><option>Kaftan</option><option>Suit / corporate wear</option><option>Event / ceremony look</option><option>Remote order</option><option>Press / collaboration</option></select><textarea required rows={6} placeholder="Tell us your preferred colour, date needed, occasion and the style you have in mind..."/><button className="button gold" type="submit">Send enquiry</button></form>:<div className="contact-success"><span>✦</span><h2>Thank you.</h2><p>Your enquiry has been captured successfully for this demo experience.</p><a className="button gold" href={contactInfo.whatsappLink} target="_blank" rel="noreferrer">Continue on WhatsApp</a></div>}</section>
</>}
